version: '3.1'

services:

  db:
    image: postgres
    container_name: pg-database
    network_mode: host
    restart: always
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD="%RaV8x3_mVqvH_Davrjv"

